spring.application.name=Capx_backend
# Local PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/coherent_outreach
spring.datasource.username=outreach
spring.datasource.password=outreach
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8443
# server.ssl.key-store=classpath:mykeystore.p12
# server.ssl.key-store-password=spidy@Hero8
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=mykey

