spring.application.name=Capx_backend
# Database Configuration supporting Environment Variables and Local Fallbacks
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coherent_outreach}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:outreach}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:outreach}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8443}
# server.ssl.key-store=classpath:mykeystore.p12
# server.ssl.key-store-password=spidy@Hero8
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=mykey

